[[redirects]]
from = "/admin/*" 
to = "/admin/:splat"
status = 200
force = true
conditions = {Role=["admin"]}

[[redirects]]
from = "/intro/*"
to = "/intro/:splat"
status = 200
conditions = {Role=["intro", "employee", "admin"]}

[[redirects]]
from = "/startit/*" 
to = "/startit/:splat"
status = 200
force = true
conditions = {Role=["startIT", "employee", "admin"]}

[[redirects]]
from = "/employee/*" 
to = "/employee/:splat"
status = 200
force = true
conditions = {Role=["employee", "admin"]}

#   Maskering av feilkoder  Omdirigering til hjemme side
[[redirects]]
from = "/*" 
to = "/"
status = 401
force = true

[[redirects]]
from = "/*"
to = "/"
status = 404
force = true
